server:
  port: 8080 #??? ??? ?? ?? ??
  #  ssl: #https ???? ??? ??? ??
  #    key-store: classpath:keystore.p12
  #    key-store-password: kimbbar3!@
  #    key-store-type: PKCS12
  #    key-alias: mysslkey
  servlet:
    encoding:
      charset: utf-8 #???? ??? ?? ??? -> utf-8? ??
      force: true # ??? ??? ?? ? ???? ??? ????? ?????.

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://jinnymo.iptime.org:3306/exam?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd123
#  datasource:
#    url: jdbc:postgresql://jinnymo.iptime.org:5432/postgres #?????? ??? ?? url ??
#    driver-class-name: org.postgresql.Driver #???? ???? ?????.
#    username: postgres #??? ???? ??
#    password: 'kimbbar3!@' #DB ????? ???? ????? ??

  #  h2:
  #    console:
  #      enabled: true #H2 ??? ??? ??? ??? ???.

  output:
    ansi:
      enabled: always #????? ansi ????? ??? ? ??? ??

#mybatis ??
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml #MyBatis ?? ?? ??? ?????. **? ?? ????? ???? *.xml? ?? xml??? ??
  configuration:
    map-underscore-to-camel-case: true # ??? ???? ????? ???(column_name)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL ?? ???? ?????.

logging:
  level:
    org.apache.ibatis: DEBUG # MyBatis ????? ???? ???? ???? SQL ??? ???? ??? ??? ????.


